name: 'Tiecd'
description: 'The CICD toolchain to simplify building and deploying applications into the cloud.' 
auth: 'dataaxiom'
branding:
  icon: 'send'
  color: 'blue'

inputs:
  basedir:
    description: 'directory containing tie.yml and deployment files  (default: . )'
    required: false
  files:
    description: 'override files to run'
    required: false
  files_commit_prefix:
    description: 'string prefixes to search for in commit message to specify files to process, i.e. file=tieapp.yaml (default: "file|files")'
    required: false
  apps:
    description: 'override which apps to run'
    required: false
  apps_commit_prefix:
    description: 'string prefixes to search for commit message to specify apps to process, i.e. apps=myapp (default: "app|apps|run|update)"'
    required: false
  file_prefix:
    description: 'file prefix for tie.yml files, (defaults: "tie")'
    required: false
  app_names_required:
    description: 'only execute the app names that are passed at runtime'
    required: false
  ignore_errors:
    description: 'ignore errors keep processing other apps'
    required: false
  verbose:
    description: 'increase logging to include all tracing and additional informational logging'
    required: false
  trace_generated:
    description: 'log generated artifacts'
    required: false
  trace_tie_file:
    description: 'log generated and expanded tie files'
    required: false
  trace_commands:
    description: 'log executed commands'
    required: false
  banner:
    description: 'show TIECD banner header during execution'
    required: false
  create_namespaces:
    description: 'auto create namespaces if necessary'
    required: false

runs:
  using: 'composite'
  steps:
    - run: ./tiecd.sh
      shell: bash

